apiVersion: v1
kind: Service
metadata:
  name: checkpayloadservice
  labels:
    app: checkpayloadservice
spec:
  type: ClusterIP
  selector:
    app: checkpayload
  ports:
    - port: 4000
      targetPort: 3000
      protocol: TCP
      name: http
  externalName: checkpayloadservice