apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:

  rules:
    - http:
        paths:
          - path: /checkpayload
            pathType: Prefix
            backend:
              service:
                name: checkpayloadservice
                port:
                  number: 4000