kind: Deployment
apiVersion: apps/v1
metadata:
  name: doing
  labels:
    app: doing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doing
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: doing
    spec:
      volumes:
        - name: doing-volume
          emptyDir: {}
      containers:
        - image: tsmarsh/queryblock
          name: checkpayload
          env:
            - name: PORT
              value: "3000"
            - name: PATH_PREFIX
              value: ""
            - name: SCHEMA_URL
              value: "file:///mnt/schema/jblocks/k8s/queries/doing.jq"
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: "/mnt/schema"
              name: doing-volume
      initContainers:
        - image: alpine/git
          name: git-preloader
          volumeMounts:
            - mountPath: "/mnt/schema"
              name: doing-volume
          command: ['git','clone', "https://github.com/tsmarsh/jblocks.git", "/mnt/schema/jblocks"]
